version: "3"
services:
  onidata:
    build: .
    image: onidata:newest
    container_name: onidata_api
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    command: >
      bash -c "python manage.py collectstatic --no-input
      && python manage.py migrate
      && python manage.py runserver"
  postgres:
    image: postgres:12.3-alpine
    container_name: onidata_postgres
    env_file: .env
    ports:
      - "5432"

  adminer:
    image: adminer
    container_name: onidata_adminer
    links:
      - postgres
    ports:
      - 8888:8080