# Generated by Django 3.1.1 on 2020-10-15 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Contract Price', max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bank',
            field=models.TextField(help_text='Information about bank', verbose_name='Contract Bank'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Interest Rate', max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Ip Adress of submission', verbose_name='Ip address'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='submission_date',
            field=models.DateField(auto_now_add=True, help_text='Submission Date'),
        ),
    ]
